// Generated by https://quicktype.io
import request from 'axios';
import { environment } from './env';

export interface OrganicResult {
  position: number;
  title: string;
  link: string;
  displayed_link: string;
  date: string;
  snippet: string;
  sitelinks: { list: string[] };
}

export async function getFashionReportGoogleSearchResult(): Promise<OrganicResult> {
  const result = await request.get(
    `https://serpapi.com/search?q=ffxiv%20fashion%20report%20this%20week&google_domain=google.com&gl=us&hl=en&num=1&api_key=${environment.serpApiKey}`
  );
  return result.data.organic_results[0];
}
